## TIRE BUILDING DEFECT PREDICTION

In [1]:
## IMPORTING ALL LIBRARIES AND DATA FILE IN JUPYTER NOTEBOOK

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('fsob1.csv')

In [3]:
data.head()

,GT BARCODE,BREAKER2 WIDTH MEASURED,BREAKER2 WIDTH SETPOINT,BREAKER2 LENGTH MEASURED,BREAKER2 LENGTH SETPOINT,BREAKER2 LE ANGLE MEASURED,BREAKER2 TE ANGLE MEASURED,BREAKER2 ANGLE SETPOINT,BREAKER2 POS WIDTH OK,BREAKER2 MEAS LENGTH AXIS,...,BT DRUM \nSPOT,T RING OFFCENTER,BT HEIGHT OFFSET,P2 LEFT,P2 MID,P2 RIGHT,P1 LEFT,P1 MID,P1 RIGHT,target
0,8307556022,152.350006,152,1988.300049,1990,0.000000,23.969999,24,1,1990.337402,...,110.0,0.8,-0.2,5.399320,6.991842,7.069561,7.419912,11.372820,8.828595,0
1,8307556023,152.350006,152,1991.599976,1990,23.730000,23.699999,24,1,1993.896484,...,110.0,0.8,-0.2,4.951153,7.160814,6.462471,5.846768,9.334384,7.384231,0
2,8307556024,151.990005,152,1989.800049,1990,23.820000,23.699999,24,1,1992.332153,...,110.0,0.8,-0.2,6.787394,7.232586,7.821528,9.118042,12.657740,9.997046,0
3,8307556025,152.270004,152,1991.000000,1990,23.680000,23.709999,24,1,1994.317017,...,110.0,0.8,-0.2,8.108207,8.721142,7.667936,7.539566,11.731160,9.576769,0
4,8307556026,152.630005,152,1993.300049,1990,23.789999,23.750000,24,1,1996.169434,...,110.0,0.8,-0.2,-5.315038,-66.711230,999.000000,5.969498,11.810520,8.540071,0

## DATA CLEANING AND INFO

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13032 entries, 0 to 13031
Data columns (total 85 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   GT BARCODE                            13032 non-null  int64
 1   BREAKER2 WIDTH MEASURED               13032 non-null  float64
 2   BREAKER2 WIDTH SETPOINT               13032 non-null  int64
 3   BREAKER2 LENGTH MEASURED              13032 non-null  float64
 4   BREAKER2 LENGTH SETPOINT              13032 non-null  int64
 5   BREAKER2 LE ANGLE MEASURED            13032 non-null  float64
 6   BREAKER2 TE ANGLE MEASURED            13032 non-null  float64
 7   BREAKER2 ANGLE SETPOINT               13032 non-null  int64
 8   BREAKER2 POS WIDTH OK                 13032 non-null  int64
 9   BREAKER2 MEAS LENGTH AXIS             13032 non-null  float64
 10  BREAKER2 USE VVS LENGTH               13032 non-null  int64
 11  BREAKER2 SPOT POSITION                13032 non-null  int64
 12  BREAKER2 CYCLE MAT AT FRONT           13032 non-null  float64
 13  BREAKER2 CYCLE TOTAL                  13032 non-null  float64
 14  BREAKER1 WIDTH MEASURED               13032 non-null  float64
 15  BREAKER1 WIDTH SETPOINT               13032 non-null  int64
 16  BREAKER1 LENGTH MEASURED              13032 non-null  float64
 17  BREAKER1 LENGTH SETPOINT              13032 non-null  int64
 18  BREAKER1 LE ANGLE MEASURED            13032 non-null  float64
 19  BREAKER1 TE ANGLE MEASURED            13032 non-null  float64
 20  BREAKER1 ANGLE SETPOINT               13032 non-null  int64
 21  BREAKER1 POS WIDTH OK                 13032 non-null  int64
 22  BREAKER1 MEAS LENGTH AXIS             13032 non-null  float64
 23  BREAKER1 USE VVS LENGTH               13032 non-null  int64
 24  BREAKER1 SPOT POSITION                13032 non-null  int64
 25  BREAKER1 CYCLE MAT AT FRONT           13032 non-null  float64
 26  BREAKER1 CYCLE TOTAL                  13032 non-null  float64
 27  CAP PLY SPOT POSITION                 13032 non-null  int64
 28  TREAD WIDTH MEASURED                  13032 non-null  float64
 29  TREAD WIDTH SETPOINT                  13032 non-null  int64
 30  TREAD LENGTH MEASURED                 13032 non-null  float64
 31  TREAD LENGTH SETPOINT                 13032 non-null  int64
 32  TREAD POS WIDTH OK                    13032 non-null  int64
 33  TREAD CYCLE MAT AT FRONT              13032 non-null  float64
 34  TREAD CYCLE TOTAL                     13032 non-null  float64
 35  PA WIDTH MEASURED   Â                  13032 non-null  float64
 36  PA WIDTH SETPOINT                     13032 non-null  int64
 37  IL LENGTH MEASURED                    13032 non-null  float64
 38  IL LENGTH SETPOINT                    13032 non-null  float64
 39  PA ANGLE MEASURED                     13032 non-null  float64
 40  PA SPOT POSITION                      13032 non-null  int64
 41  BARCODE SPOT POS                      13032 non-null  int64
 42  PA CYCLE MAT AT FRONT                 13032 non-null  float64
 43  PA CYCLE TOTAL                        13032 non-null  float64
 44  BODY PLY1 LENGTH MEASURED             13032 non-null  float64
 45  BODY PLY1 LENGTH SETPOINT             13032 non-null  float64
 46  BODY PLY1 WIDTH SETPOINT              13032 non-null  int64
 47  BODY PLY1 SPOT POS                    13032 non-null  int64
 48  1PLO CONTAINS BP 1 OR 2               13032 non-null  int64
 49  BODY PLY1 MONO OR TWOPLY              13032 non-null  int64
 50  BODY PLY1 TOTAL SCRAP CUTOUT          13032 non-null  float64
 51  BODY PLY BP1 CYCLE REST               13032 non-null  float64
 52  BODY PLY2 LENGTH MEASURED             13032 non-null  float64
 53  BODY PLY2 LENGTH SETPOINT             13032 non-null  float64
 54  BODY PLY2 WIDTH SETPOINT              13032 non-null  int64
 55  BODY PLY2 SPOT POS                    13032 non-null  int64
 56  2PLO CONTAINS BP 1 OR 2               13032 non-null  int64
 57  BODY PLY2 MONO OR TWOPLY              13032 non-null  int64
 58  BODY PLY2 TOTAL SCRAP CUTOUT          13032 non-null  float64
 59  BODY PLY BP2 CYCLE REST               13032 non-null  float64
 60  ISDS AMOUNT SPLICES BP1               13032 non-null  int64
 61  ISDS AMOUNT SPLICES BP2               13032 non-null  int64
 62  CARCASS DRUM DRUM SIZE                13032 non-null  int64
 63  CARCASS DRUM TURNUP PRESSURE MIN      13032 non-null  float64
 64  CARCASS DRUM TURNUP PRESSURE MAX      13032 non-null  float64
 65  CARCASS DRUM PRESHAPE PRESSURE MIN    13032 non-null  float64
 66  CARCASS DRUM PRESHAPE PRESSURE MAX    13032 non-null  float64
 67  CARCASS DRUM SHAPE PRESSURE MIN       13032 non-null  float64
 68  CARCASS DRUM SHAPE PRESSURE MAX       13032 non-null  float64
 69  CARCASS DRUM STITCH TD PRESSURE MIN   13032 non-null  float64
 70  CARCASS DRUM STITCH TD PRESSURE MAX   13032 non-null  float64
 71  B&T PREP CYCLE TIME WAIT CC           13032 non-null  float64
 72  CHAFER
SPOT                          13030 non-null  float64
 73  B2 RIGHT                              13030 non-null  float64
 74  CC DRUM
SPOT                         13030 non-null  float64
 75  BT DRUM
SPOT                         13030 non-null  float64
 76  T RING OFFCENTER                      13030 non-null  float64
 77  BT HEIGHT OFFSET                      13030 non-null  float64
 78  P2 LEFT                               13030 non-null  float64
 79  P2 MID                                13030 non-null  float64
 80  P2 RIGHT                              13030 non-null  float64
 81  P1 LEFT                               13030 non-null  float64
 82  P1 MID                                13030 non-null  float64
 83  P1 RIGHT                              13030 non-null  float64
 84  target                                13032 non-null  int64
dtypes: float64(53), int64(32)
memory usage: 8.5 MB

In [5]:
data.shape

(13032, 85)

In [6]:
data.isnull().sum()

GT BARCODE                     0
BREAKER2 WIDTH MEASURED        0
BREAKER2 WIDTH SETPOINT        0
BREAKER2 LENGTH MEASURED       0
BREAKER2 LENGTH SETPOINT       0
                              ..
P2 RIGHT                       2
P1 LEFT                        2
P1 MID                         2
P1 RIGHT                       2
target                         0
Length: 85, dtype: int64

In [7]:
data.fillna('na')

,GT BARCODE,BREAKER2 WIDTH MEASURED,BREAKER2 WIDTH SETPOINT,BREAKER2 LENGTH MEASURED,BREAKER2 LENGTH SETPOINT,BREAKER2 LE ANGLE MEASURED,BREAKER2 TE ANGLE MEASURED,BREAKER2 ANGLE SETPOINT,BREAKER2 POS WIDTH OK,BREAKER2 MEAS LENGTH AXIS,...,BT DRUM \nSPOT,T RING OFFCENTER,BT HEIGHT OFFSET,P2 LEFT,P2 MID,P2 RIGHT,P1 LEFT,P1 MID,P1 RIGHT,target
0,8307556022,152.350006,152,1988.300049,1990,0.000000,23.969999,24,1,1990.337402,...,110.0,0.8,-0.2,5.39932,6.991842,7.069561,7.419912,11.37282,8.828595,0
1,8307556023,152.350006,152,1991.599976,1990,23.730000,23.699999,24,1,1993.896484,...,110.0,0.8,-0.2,4.951153,7.160814,6.462471,5.846768,9.334384,7.384231,0
2,8307556024,151.990005,152,1989.800049,1990,23.820000,23.699999,24,1,1992.332153,...,110.0,0.8,-0.2,6.787394,7.232586,7.821528,9.118042,12.65774,9.997046,0
3,8307556025,152.270004,152,1991.000000,1990,23.680000,23.709999,24,1,1994.317017,...,110.0,0.8,-0.2,8.108207,8.721142,7.667936,7.539566,11.73116,9.576769,0
4,8307556026,152.630005,152,1993.300049,1990,23.789999,23.750000,24,1,1996.169434,...,110.0,0.8,-0.2,-5.315038,-66.71123,999.0,5.969498,11.81052,8.540071,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13027,8307823539,151.270004,152,1991.900024,1990,23.580000,23.740000,24,1,1993.603882,...,110.0,-0.05,-0.2,4.852416,2.841564,4.430395,5.616789,5.291764,7.083813,0
13028,8307823540,151.479996,152,1988.900024,1990,23.519999,23.699999,24,1,1991.146362,...,110.0,-0.05,-0.2,4.257321,2.671361,4.856722,6.674609,5.808831,6.767297,0
13029,8307823541,151.839996,152,1989.699951,1990,23.539999,23.680000,24,1,1990.527710,...,110.0,-0.05,-0.2,999.0,2.97465,4.21959,999.0,4.60921,5.02272,0
13030,8307823542,151.639999,152,1990.800049,1990,23.619999,23.699999,24,1,1991.937866,...,110.0,-0.05,-0.2,3.567693,3.390929,4.31638,4.451106,2.653931,5.905416,0
13031,8307823543,151.839996,152,1988.300049,1990,23.639999,23.689999,24,1,1990.767944,...,110.0,-0.05,-0.2,3.553339,3.149774,5.377583,5.985493,999.0,7.493837,0

In [8]:
data = data.dropna()

In [9]:
data.isnull().sum()

GT BARCODE                     0
BREAKER2 WIDTH MEASURED        0
BREAKER2 WIDTH SETPOINT        0
BREAKER2 LENGTH MEASURED       0
BREAKER2 LENGTH SETPOINT       0
                              ..
P2 RIGHT                       0
P1 LEFT                        0
P1 MID                         0
P1 RIGHT                       0
target                         0
Length: 85, dtype: int64

In [10]:
data.describe()

,GT BARCODE,BREAKER2 WIDTH MEASURED,BREAKER2 WIDTH SETPOINT,BREAKER2 LENGTH MEASURED,BREAKER2 LENGTH SETPOINT,BREAKER2 LE ANGLE MEASURED,BREAKER2 TE ANGLE MEASURED,BREAKER2 ANGLE SETPOINT,BREAKER2 POS WIDTH OK,BREAKER2 MEAS LENGTH AXIS,...,BT DRUM \nSPOT,T RING OFFCENTER,BT HEIGHT OFFSET,P2 LEFT,P2 MID,P2 RIGHT,P1 LEFT,P1 MID,P1 RIGHT,target
count,1.303000e+04,13030.000000,13030.0,13030.000000,13030.0,13030.000000,13030.000000,13030.0,13030.000000,13030.000000,...,13030.0,13030.000000,1.303000e+04,13030.000000,13030.000000,13030.000000,13030.000000,13030.000000,13030.000000,13030.000000
mean,8.307722e+09,152.170376,152.0,1983.234259,1990.0,23.498917,23.802152,24.0,0.977360,1990.953991,...,110.0,0.052475,-2.000000e-01,54.893209,116.019560,9.071247,52.360784,118.608155,9.494309,0.007982
std,7.352716e+04,2.459932,0.0,107.278482,0.0,2.350225,0.550108,0.0,0.148759,1.922562,...,0.0,0.117637,1.376729e-14,215.126645,311.273420,52.920900,207.304110,313.706997,46.027128,0.126098
min,8.307556e+09,0.000000,152.0,0.000000,1990.0,0.000000,0.000000,24.0,0.000000,1953.342285,...,110.0,-0.200000,-2.000000e-01,-101.955700,-107.962200,-102.796900,-98.630580,-117.860100,-99.655080,0.000000
25%,8.307693e+09,151.979996,152.0,1988.099976,1990.0,23.680000,23.760000,24.0,1.000000,1990.002563,...,110.0,0.050000,-2.000000e-01,4.709691,5.114435,4.584705,5.756360,6.410999,5.978623,0.000000
50%,8.307744e+09,152.199997,152.0,1989.099976,1990.0,23.740000,23.830000,24.0,1.000000,1991.024292,...,110.0,0.050000,-2.000000e-01,6.104430,6.801953,6.188301,7.078071,7.867514,7.497066,0.000000
75%,8.307772e+09,152.419998,152.0,1990.099976,1990.0,23.799999,23.889999,24.0,1.000000,1992.004211,...,110.0,0.050000,-2.000000e-01,7.512703,8.526536,8.121485,8.384504,9.448733,8.939893,0.000000
max,8.307824e+09,157.479996,152.0,2006.800049,1990.0,25.309999,25.000000,24.0,1.000000,2008.545532,...,110.0,0.800000,-2.000000e-01,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,2.000000

## Train and Split data

In [11]:
x = data.drop(['target','GT BARCODE'], axis =1)

In [12]:
x

,BREAKER2 WIDTH MEASURED,BREAKER2 WIDTH SETPOINT,BREAKER2 LENGTH MEASURED,BREAKER2 LENGTH SETPOINT,BREAKER2 LE ANGLE MEASURED,BREAKER2 TE ANGLE MEASURED,BREAKER2 ANGLE SETPOINT,BREAKER2 POS WIDTH OK,BREAKER2 MEAS LENGTH AXIS,BREAKER2 USE VVS LENGTH,...,CC DRUM \nSPOT,BT DRUM \nSPOT,T RING OFFCENTER,BT HEIGHT OFFSET,P2 LEFT,P2 MID,P2 RIGHT,P1 LEFT,P1 MID,P1 RIGHT
0,152.350006,152,1988.300049,1990,0.000000,23.969999,24,1,1990.337402,0,...,30.0,110.0,0.80,-0.2,5.399320,6.991842,7.069561,7.419912,11.372820,8.828595
1,152.350006,152,1991.599976,1990,23.730000,23.699999,24,1,1993.896484,0,...,30.0,110.0,0.80,-0.2,4.951153,7.160814,6.462471,5.846768,9.334384,7.384231
2,151.990005,152,1989.800049,1990,23.820000,23.699999,24,1,1992.332153,0,...,30.0,110.0,0.80,-0.2,6.787394,7.232586,7.821528,9.118042,12.657740,9.997046
3,152.270004,152,1991.000000,1990,23.680000,23.709999,24,1,1994.317017,0,...,30.0,110.0,0.80,-0.2,8.108207,8.721142,7.667936,7.539566,11.731160,9.576769
4,152.630005,152,1993.300049,1990,23.789999,23.750000,24,1,1996.169434,0,...,30.0,110.0,0.80,-0.2,-5.315038,-66.711230,999.000000,5.969498,11.810520,8.540071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13027,151.270004,152,1991.900024,1990,23.580000,23.740000,24,1,1993.603882,0,...,30.0,110.0,-0.05,-0.2,4.852416,2.841564,4.430395,5.616789,5.291764,7.083813
13028,151.479996,152,1988.900024,1990,23.519999,23.699999,24,1,1991.146362,0,...,30.0,110.0,-0.05,-0.2,4.257321,2.671361,4.856722,6.674609,5.808831,6.767297
13029,151.839996,152,1989.699951,1990,23.539999,23.680000,24,1,1990.527710,0,...,30.0,110.0,-0.05,-0.2,999.000000,2.974650,4.219590,999.000000,4.609210,5.022720
13030,151.639999,152,1990.800049,1990,23.619999,23.699999,24,1,1991.937866,0,...,30.0,110.0,-0.05,-0.2,3.567693,3.390929,4.316380,4.451106,2.653931,5.905416
13031,151.839996,152,1988.300049,1990,23.639999,23.689999,24,1,1990.767944,0,...,30.0,110.0,-0.05,-0.2,3.553339,3.149774,5.377583,5.985493,999.000000,7.493837

In [13]:
y = data['target']

In [14]:
y.value_counts()

0    12978
2       52
Name: target, dtype: int64

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=14, test_size =0.3)

In [16]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(9121, 83) (3909, 83) (9121,) (3909,)

## model selection

In [40]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [41]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [42]:
pred = model.predict(x_test)

## Model accuracy score

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy = accuracy_score(pred,y_test)

In [45]:
accuracy

0.9976976208749041

In [48]:
input = (152.3500061,152,1990.800049,1990,23.68999863,23.84000015,24,1,1991.854736,0,80,26.25799942,61.39300156,166.3200073,164,1978.5,1983,24.12999916,24.12999916,24,1,1982.71936,0,260,26.72900009,61.43000031,290,214.9900055,212,2013.247803,2015,1,18.8029995,61.50400162,730.3061523,733,1213.137939,1211,-0.761187196,190,170,12.75599957,68.47699738,1228.342529,1228,564,210,1,2,0,6.857999802,1230.348145,1229,508,90,2,2,0,27.55900002,2,2,16,0.599511623,0.599511623,0.406593412,0.406593412,0.186813191,0.186813191,1.002442002,1.002442002,9.045999527,270,0.7773405,30,110,0.05,-0.2,5.682307,11.86087,5.618737,6.62324,6.621703,7.078686)
input = np.asarray(input)

input1 = input.reshape(1,-1)

model.predict(input1)

C:\Users\91772\anconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)